version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local:2.4.0
    container_name: dynamodb
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup /home/dynamodblocal/data
    volumes:
      - ./data:/home/dynamodblocal/data
    ports:
      - '8000:8000'
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.3.0
    container_name: dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb:8000'
      AWS_REGION: 'dummy'
      AWS_ACCESS_KEY_ID: 'dummy'
      AWS_SECRET_ACCESS_KEY: 'dummy'
    depends_on:
      - dynamodb
  awscli:
    container_name: awscli
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['']
    tty: true
    command:
      - /bin/sh
    volumes:
      - './src:/opt/dynamo/src'
volumes:
  dynamodb:
    driver: local
