version: '3.8'
services:
  sqs:
    container_name: sqs
    image: softwaremill/elasticmq-native:1.4.0
    ports:
      - '9324:9324'
      - '9325:9325'
    volumes:
      - ./custom.conf:/opt/elasticmq.conf
