version: '3.8'
services:
  s3:
    container_name: s3
    image: minio/minio:RELEASE.2023-01-18T04-36-38Z
    environment:
      MINIO_ROOT_USER: dummy_access_key
      MINIO_ROOT_PASSWORD: dummy_secret_access_key
    command: ['server', '/data', '--console-address', ':9090']
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ./data:/data
  mc:
    container_name: mc
    image: minio/mc:RELEASE.2022-12-24T15-21-38Z
    depends_on:
      - s3
    environment:
      MINIO_ROOT_USER: dummy_access_key
      MINIO_ROOT_PASSWORD: dummy_secret_access_key
    entrypoint: >
      /bin/sh -c "
      mc alias set s3 http://s3:9000 dummy_access_key dummy_secret_access_key;
      mc mb --ignore-existing s3/default-bucket;
      "
